Get credentials at first curl run

diff --git a/bin/github-do b/bin/github-do
--- a/bin/github-do
+++ b/bin/github-do
@@ -364,6 +364,80 @@ function out:fail {
 function out:error {
     echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
 }
+##bash-libs: bincheck.sh @ 266ad599 (after 1.1.4)
+
+### bincheck:get COMMANDS ... Usage:bbuild
+#
+# Return the first existing binary
+#
+# Useful for finding an appropriate binary when you know
+# different systems may supply binaries under different names.
+#
+# Returns the full path from `which` for the first executable
+# encountered.
+#
+# Example:
+#
+# 	bincheck:get markdown_py markdown ./mymarkdown
+#
+# Tries in turn to get a `markdown_py`, then a `markdown`, and then a local `./mymarkdown`
+#
+###/doc
+
+bincheck:get() {
+    local BINEXE=
+    for binname in "$@"; do
+        # Some implementations of `which` print error messages
+        # Not useful here.
+        BINEXE=$(which "$binname" 2>/dev/null)
+
+        if [[ -n "$BINEXE" ]]; then
+            echo "$BINEXE"
+            return 0
+        fi
+    done
+    return 1
+}
+
+### bincheck:has NAMES ... Usage:bbuild
+#
+# Determine if at least one of the binaries listed is present and installed on the system
+#
+###/doc
+
+bincheck:has() {
+    [[ -n "$(bincheck:get "$@")" ]]
+}
+
+### bincheck:path NAME Usage:bbuild
+#
+# Determine the actual path to the command
+#
+# Relative paths are not expanded.
+#
+###/doc
+
+bincheck:path() {
+    local binname="$1"; shift || :
+
+    [[ "$binname" =~ / ]] && { 
+        # A relative path cannot be resolved, just check existence
+        [[ -e "$binname" ]] && echo "$binname" || return 1
+
+    } || binname="$(which "$binname" 2>/dev/null)"
+
+    # `which` failed
+    [[ -n "$binname" ]] || return 1
+
+    [[ -h "$binname" ]] && {
+
+        local pointedname="$(ls -l "$binname"|grep -oP "$binname.+"|sed "s|$binname -> ||")"
+        bincheck:path "$pointedname" ; return "$?"
+    
+    } || echo "$binname"
+}
+
+
 ##bash-libs: askuser.sh @ 266ad599 (after 1.1.4)
 
 ### askuser Usage:bbuild
@@ -489,84 +563,18 @@ function askuser:choose {
         fi
     done
 }
-##bash-libs: bincheck.sh @ 266ad599 (after 1.1.4)
-
-### bincheck:get COMMANDS ... Usage:bbuild
-#
-# Return the first existing binary
-#
-# Useful for finding an appropriate binary when you know
-# different systems may supply binaries under different names.
-#
-# Returns the full path from `which` for the first executable
-# encountered.
-#
-# Example:
-#
-# 	bincheck:get markdown_py markdown ./mymarkdown
-#
-# Tries in turn to get a `markdown_py`, then a `markdown`, and then a local `./mymarkdown`
-#
-###/doc
-
-bincheck:get() {
-    local BINEXE=
-    for binname in "$@"; do
-        # Some implementations of `which` print error messages
-        # Not useful here.
-        BINEXE=$(which "$binname" 2>/dev/null)
-
-        if [[ -n "$BINEXE" ]]; then
-            echo "$BINEXE"
-            return 0
-        fi
-    done
-    return 1
-}
-
-### bincheck:has NAMES ... Usage:bbuild
-#
-# Determine if at least one of the binaries listed is present and installed on the system
-#
-###/doc
-
-bincheck:has() {
-    [[ -n "$(bincheck:get "$@")" ]]
-}
-
-### bincheck:path NAME Usage:bbuild
-#
-# Determine the actual path to the command
-#
-# Relative paths are not expanded.
-#
-###/doc
-
-bincheck:path() {
-    local binname="$1"; shift || :
-
-    [[ "$binname" =~ / ]] && { 
-        # A relative path cannot be resolved, just check existence
-        [[ -e "$binname" ]] && echo "$binname" || return 1
-
-    } || binname="$(which "$binname" 2>/dev/null)"
-
-    # `which` failed
-    [[ -n "$binname" ]] || return 1
-
-    [[ -h "$binname" ]] && {
-
-        local pointedname="$(ls -l "$binname"|grep -oP "$binname.+"|sed "s|$binname -> ||")"
-        bincheck:path "$pointedname" ; return "$?"
-    
-    } || echo "$binname"
-}
-
 
 gh:curl() {
+    gh:getcreds
     ( set -x
     curl -s -S -u "$GHUSER:$GHTOKEN" "$@"
     )
+}
+
+gh:getcreds() {
+    [[ -n "${GHUSER:-}" ]] || GHUSER="$(askuser:ask "Github user name")"
+    [[ -n "${GHTOKEN:-}" ]] || GHTOKEN="$(askuser:password "Github Personal Access Token"; echo >&2)"
+    export GHUSER GHTOKEN
 }
 
 gh:repo:create() {
@@ -705,7 +713,6 @@ gh:main() {
 
     case "$action" in
     rename|reown|delete|create|srename)
-        gh:getcreds
         gh:repo:"$action" "$@"
         ;;
     branch|tag)
@@ -723,12 +730,6 @@ gh:main() {
         out:fail "Unknown action '$action'"
         ;;
     esac
-}
-
-gh:getcreds() {
-    [[ -n "${GHUSER:-}" ]] || GHUSER="$(askuser:ask "Github user name")"
-    [[ -n "${GHTOKEN:-}" ]] || GHTOKEN="$(askuser:password "Github Personal Access Token"; echo >&2)"
-    export GHUSER GHTOKEN
 }
 
 gh:jqcheck() {
